---
- name: Remove immutable flag from resolv.conf
  ansible.builtin.command: chattr -i /etc/resolv.conf
  when: dns_servers is defined and dns_servers | length > 0
  failed_when: false
  changed_when: false

- name: Configure DNS servers
  ansible.builtin.copy:
    dest: /etc/resolv.conf
    content: |
      {% for dns in dns_servers %}
      nameserver {{ dns }}
      {% endfor %}
    mode: '0644'
  when: dns_servers is defined and dns_servers | length > 0
  register: resolv_changed

- name: Protect resolv.conf from being overwritten
  ansible.builtin.command: chattr +i /etc/resolv.conf
  when: dns_servers is defined and dns_servers | length > 0
  failed_when: false
  changed_when: true
